"use client";

import React, { useState } from "react";
import { Sidebar } from "@/components/sidebar/Sidebar";
import { AppHeader } from "@/components/layout/AppHeader";
import { ChatWindow } from "@/components/chat/ChatWindow";
import { RightPanel } from "@/components/context/RightPanel";
import {
  initialConversationDetails,
  initialTools,
  quickPrompts,
} from "@/data/mockData";
import { Message, AutonomyMode, NavTab, PendingAction, NORTHSTAR_USER_CONTEXT } from "@/types/chat";

const API_ROOT =
  process.env.NEXT_PUBLIC_API_BASE_URL ||
  process.env.NEXT_PUBLIC_API_URL ||
  "http://localhost:8000";
const API_BASE = `${API_ROOT.replace(/\/$/, "")}/api/v1`;

export default function Home() {
  const [autonomyMode, setAutonomyMode] = useState<AutonomyMode>("copilot");
  const [activeTab, setActiveTab] = useState<NavTab>("ai-support");
  const [messages, setMessages] = useState<Message[]>([]);
  const [pendingAction, setPendingAction] = useState<PendingAction | null>(null);
  const [mobileSidebarOpen, setMobileSidebarOpen] = useState(false);
  const [mobileRightPanelOpen, setMobileRightPanelOpen] = useState(false);

  const handleSendMessage = async (text: string) => {
    const timeNow = new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
    const userMsg: Message = {
      id: `usr-${Date.now()}`,
      sender: "user",
      content: text,
      timestamp: timeNow,
    };

    const thinkingMsgId = `thinking-${Date.now()}`;
    const thinkingMsg: Message = {
      id: thinkingMsgId,
      sender: "assistant",
      content: "",
      timestamp: timeNow,
      isThinking: true,
    };

    setMessages((prev) => [...prev, userMsg, thinkingMsg]);

    try {
      const res = await fetch(`${API_BASE}/agent/chat`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          message: text,
          conversation_id: "conv_session_1",
          user_context: NORTHSTAR_USER_CONTEXT,
        }),
      });

      if (!res.ok) {
        throw new Error(`Agent API returned ${res.status}: ${res.statusText}`);
      }

      const data = await res.json();

      const assistantMsg: Message = {
        id: `ai-${Date.now()}`,
        sender: "assistant",
        content: data.response || "No response generated by agent.",
        timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
        agentSteps: (data.activity || []).map((label: string, idx: number) => ({
          id: `st-${idx}`,
          type: "success",
          label,
          timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" }),
        })),
        sources: (data.sources || []).map((s: { document: string; page: number; authority?: string }, idx: number) => ({
          id: `src-${idx}`,
          title: `${s.document} (Page ${s.page})`,
          category:
            s.authority === "customer_agreement"
              ? "Customer Agreement"
              : s.authority === "sop"
                ? "SOP"
                : "Policy",
        })),
      };

      setMessages((prev) => prev.map((m) => (m.id === thinkingMsgId ? assistantMsg : m)));

      if (data.pending_action) {
        const pa = data.pending_action;
        setPendingAction({
          id: pa.action_id,
          action_id: pa.action_id,
          actionType: pa.summary || "Escalate Ticket",
          customer: pa.customer || "Unknown",
          ticket: pa.ticket_id || "Unknown",
          reason: pa.reason || "Pending escalation",
          priority: pa.priority === "high" ? "High" : "Medium",
          status: "pending_approval",
        });
      } else {
        setPendingAction(null);
      }
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : "Unknown error";
      console.error("Error communicating with ParcelPilot AI Backend:", err);
      const fallbackMsg: Message = {
        id: `err-${Date.now()}`,
        sender: "assistant",
        content: `Failed to communicate with backend: ${message}. Ensure FastAPI server is running on ${API_ROOT}.`,
        timestamp: timeNow,
      };
      setMessages((prev) => prev.map((m) => (m.id === thinkingMsgId ? fallbackMsg : m)));
    }
  };

  const handleApproveAction = async () => {
    if (!pendingAction?.action_id) return;

    try {
      const res = await fetch(`${API_BASE}/actions/${pendingAction.action_id}/confirm`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ user_context: NORTHSTAR_USER_CONTEXT }),
      });
      if (!res.ok) {
        throw new Error(`Confirm action failed: ${res.status}`);
      }
      const data = await res.json();
      setPendingAction((prev) => (prev ? { ...prev, status: "approved" } : null));
      const sysMsg: Message = {
        id: `sys-${Date.now()}`,
        sender: "system",
        content: `Action Confirmed & Executed: ${data.result?.message || pendingAction.actionType}`,
        timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
      };
      setMessages((prev) => [...prev, sysMsg]);
    } catch (err) {
      console.error("Error confirming action:", err);
      const sysMsg: Message = {
        id: `sys-${Date.now()}`,
        sender: "system",
        content: "Failed to confirm action. Please try again.",
        timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
      };
      setMessages((prev) => [...prev, sysMsg]);
    }
  };

  const handleCancelAction = async () => {
    if (!pendingAction?.action_id) return;

    try {
      const res = await fetch(`${API_BASE}/actions/${pendingAction.action_id}/reject`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ user_context: NORTHSTAR_USER_CONTEXT }),
      });
      if (!res.ok) {
        throw new Error(`Reject action failed: ${res.status}`);
      }
      setPendingAction((prev) => (prev ? { ...prev, status: "cancelled" } : null));
      const sysMsg: Message = {
        id: `sys-${Date.now()}`,
        sender: "system",
        content: "Escalation request was rejected by human executive.",
        timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
      };
      setMessages((prev) => [...prev, sysMsg]);
    } catch (err) {
      console.error("Error rejecting action:", err);
      const sysMsg: Message = {
        id: `sys-${Date.now()}`,
        sender: "system",
        content: "Failed to reject action. Please try again.",
        timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
      };
      setMessages((prev) => [...prev, sysMsg]);
    }
  };

  return (
    <div className="flex h-screen bg-slate-100/60 text-slate-800 overflow-hidden font-sans">
      <Sidebar
        activeTab={activeTab}
        onSelectTab={setActiveTab}
        className="hidden md:flex"
      />

      {mobileSidebarOpen && (
        <div className="fixed inset-0 z-50 flex md:hidden">
          <div
            className="fixed inset-0 bg-slate-900/40 backdrop-blur-xs"
            onClick={() => setMobileSidebarOpen(false)}
          />
          <Sidebar
            activeTab={activeTab}
            onSelectTab={(tab) => {
              setActiveTab(tab);
              setMobileSidebarOpen(false);
            }}
            className="relative z-10 w-64 shadow-xl"
          />
        </div>
      )}

      <div className="flex-1 flex flex-col h-full min-w-0 overflow-hidden">
        <AppHeader
          mode={autonomyMode}
          onChangeMode={setAutonomyMode}
          onToggleSidebar={() => setMobileSidebarOpen(true)}
          onToggleRightPanel={() => setMobileRightPanelOpen(true)}
        />

        <div className="flex-1 flex min-h-0 overflow-hidden">
          <ChatWindow
            messages={messages}
            onSendMessage={handleSendMessage}
            quickPrompts={quickPrompts}
          />

          <RightPanel
            conversationDetails={initialConversationDetails}
            tools={initialTools}
            pendingAction={pendingAction}
            mode={autonomyMode}
            onApproveAction={handleApproveAction}
            onCancelAction={handleCancelAction}
            className="hidden xl:block"
          />
        </div>
      </div>

      {mobileRightPanelOpen && (
        <div className="fixed inset-0 z-50 flex justify-end xl:hidden">
          <div
            className="fixed inset-0 bg-slate-900/40 backdrop-blur-xs"
            onClick={() => setMobileRightPanelOpen(false)}
          />
          <RightPanel
            conversationDetails={initialConversationDetails}
            tools={initialTools}
            pendingAction={pendingAction}
            mode={autonomyMode}
            onApproveAction={handleApproveAction}
            onCancelAction={handleCancelAction}
            onCloseMobile={() => setMobileRightPanelOpen(false)}
            className="relative z-10 w-80 shadow-2xl"
          />
        </div>
      )}
    </div>
  );
}
